### ISSUE TITLE
Add support for ad insertion by users (Kleinanzeigen)

### ISSUE THREAD

**Issue by RunningJoke** [RunningJoke/allipunkte#27]
Each user should be able to inject advertisements for actions he is willing to offer points for.

Each advertisments consists of:

- Created by user
- created date
- action title
- date of action
- action description (text only) (optional)

- [ ] create entity and entity listeners to create the ads
- [ ] add endpoint security for ads

in the frontend:

- [ ] add view support for the ads
- [ ] add endpoint for updating/withdrawing the ad
- [ ] add easy way to create ads
- [ ] add ability to export event to calendar

**Comment by joechickn** [comment]
Adding status for ads: Active, Accepted, Past Due Date
