### ISSUE TITLE
Ebay Classifieds (Kleinanzeigen) 

### ISSUE THREAD

**Issue by joechickn** [RunningJoke/allipunkte#28]
Enable user to place requests for help in exchange for x allitaler. 

Name: "Anschreiber H1 am xx.xx.xxxx  für 4 Allitaler und 1 Kiste"
When: xx/yy, dd/mm/yyyy
Created by: username

**Comment by joechickn** [comment]
Status: open, accepted, past due date !?

**Comment by RunningJoke** [comment]
Already discussed and started planning for it in issue #27 

Closed as duplicate (always wanted to write this)
